namespace markisa.network {

public class EntertainmentZone1
{

public static MksConnectZone Data { get; set; } = new MksConnectZone {
    Background = "res://apps/passionfruit/connect/backgrounds/entertainment.png",
    Music = "res://apps/passionfruit/connect/music/garbageGoodCorporate.mp3",
    Month = 1,
    Posts = new MksPost[] {
        new MksPost {
            User = "Unemployed Guy",
            ProfilePicture = "res://os/assets/userIcons/cat.png",
            Content = "MOVIE: THE MOVIE: PART II: PART II HAS A WOMAN!!!!!!!!!!!\n\nTHE MOVIE THE MOVIE PART II FRANCHISE HAS GONE WOKE :(",
            Replies = new MksPost[] {
                new MksPost {
                    User = "Unemployed Guy Jr.",
                    ProfilePicture = "res://os/assets/userIcons/cat.png",
                    Content = "The industrial revolution and its consequences have been a disaster for the human race."
                }
            }
        },

        new MksPost {
            User = "Netfilms",
            ProfilePicture = "res://os/assets/userIcons/cat.png",
            Verified = true,
            Content = "Movie: The Movie: Part II: Part II has the first woman in human history.",
            Replies = new MksPost[] {
                new MksPost {
                    User = "Left Westson",
                    ProfilePicture = "res://os/assets/userIcons/cat.png",
                    Verified = true,
                    Content = "The absolute legend, they never miss!"
                },

                new MksPost {
                    User = "Right McEast",
                    ProfilePicture = "res://os/assets/userIcons/cat.png",
                    Verified = true,
                    Content = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR HHHHHHHAHYTUEYSIOHGTRESBHRRRRUOPAHYRISZ7HYT89AYHT8EAHYNTFUIEHNGTUENHAOTHEDNA8O8Y8HYFGEAGTHIAHTNGIOEAHNAGE7AYIGHUOAFTHEYAYNH7AYHTYAv"
                }
            }
        },

        new MksPost {
            User = "Funny Cartoon Man",
            ProfilePicture = "res://os/assets/userIcons/cat.png",
            Verified = true,
            Content = "WATCH MY LATEST VIDEO ABOUT ADULT JOKES IN CARTOONS",
            Replies = new MksPost[] {
                new MksPost {
                    User = "Unemployed Guy Jr.",
                    ProfilePicture = "res://os/assets/userIcons/cat.png",
                    Content = "The absolute legend, he never pisses!"
                },

                new MksPost {
                    User = "Funny Cartoon Man",
                    ProfilePicture = "res://os/assets/userIcons/cat.png",
                    Verified = true,
                    Content = "<ping>Unemployed Guy Jr.</ping> i have hydration issues"
                }
            }
        },
    }
};

}

}